### PR TITLE
Merge new changes

### PR DESCRIPTION
**Pull request by Ngseri**
# Added below code block to elgg-plugin.php
if (elgg_get_plugin_setting('ical_import_export', 'event_calendar') == "yes") {
    set_input('ical_calendar_title_menu', true);
}

# Used the original event_calendar code in models/model.php
 $event_calendar_listing_format = elgg_get_plugin_setting('listing_format', 'event_calendar');
  $event_calendar_listing_format = elgg_trigger_plugin_hook('event_calendar', 'get-listing-format', [], $event_calendar_listing_format);
NOT
//$event_calendar_listing_format = get_input('format', elgg_get_plugin_setting('listing_format', 'event_calendar'));

# Used lightbox instead of colorbox in js/event_calendar/event_calendar_fullcalendar.js

### CODE REVIEW

**Comment by dploeger** [comment]
Hey, thanks for the pull request. Could you please elaborate on *why* you did what you did. It's not really clear to me. Why i.e. did you replace the elgg_load_library with require_once? Was elgg_load_library deprecated or something?

Thanks.

**Comment by Ngseri** [comment]
elgg_load_library was removed form Elgg3.

I added this set_input('ical_calendar_title_menu', true); in event_calendar/elgg-plugin.php. Because if it's not set, the 'Export' or 'Import' button will not show.

This does not return the right value for me when adding custom formats - **$event_calendar_listing_format = get_input('format', elgg_get_plugin_setting('listing_format', 'event_calendar'))**; But the original code does.

Thanks.

**Comment by dploeger** [comment]
Thanks for the clarification.

Hm. This breaks our internal testing suite here: https://github.com/wabuehamm/members.test/blob/d5772eeee50a6bfadceaa131959094b97e4ee01b/cypress/integration/appointments/paged_spec.ts#L46

It seems as through your changes the tabs are not valid Elgg tabs anymore because they usually include an li-element with a data-menu-item property.

Does that make any sense to you and can you spot the change that might've introduced this?

**Comment by dploeger** [comment]
@Ngseri I also saw, that this PR is against master. Our Elgg-3 modifications are in the issue-14 branch. Do you maybe want to check out our issue-14 branch for Elgg-3? I'll go ahead and close this PR for the time being. Reopen it, if you have any news.

**Pull request closed without merging**
